### ISSUE TITLE
Launchrctl - Go error when executed outside of project dir

### ISSUE THREAD

**Issue by lexbritvin** [launchrctl/launchr#63]
- Executing a launchr command outside of a directory with actions sometimes fails with a golang error:
```
➜  Sources launchr update
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x935b23]

goroutine 1 [running]:
github.com/launchrctl/launchr/pkg/action.ConvertInputToTplVars({0x0, 0x0, {0x0, 0x0}, {0x0, 0x0, 0x0}}, 0x0)
	github.com/launchrctl/launchr@v0.12.0/pkg/action/loader.go:136 +0xa3
github.com/launchrctl/launchr/pkg/action.inputProcessor.Process({}, {0x93f473?}, {0xc0002bc840, 0x2a3, 0x2c0})
	github.com/launchrctl/launchr@v0.12.0/pkg/action/loader.go:87 +0xeb
github.com/launchrctl/launchr/pkg/action.(*pipeProcessor).Process(0x2de?, {0x0?}, {0xc00021a600?, 0xc000013980?, 0xc000013978?})
	github.com/launchrctl/launchr@v0.12.0/pkg/action/loader.go:46 +0x5e
github.com/launchrctl/launchr/pkg/action.(*yamlFileLoader).Load(0xc0004a2000, {0xc0000ec790?})
	github.com/launchrctl/launchr@v0.12.0/pkg/action/yaml.discovery.go:92 +0x7d
github.com/launchrctl/launchr/pkg/action.(*Action).EnsureLoaded(...)
	github.com/launchrctl/launchr@v0.12.0/pkg/action/action.go:126
github.com/launchrctl/launchr.(*appImpl).init(0xc0003c0210)
	github.com/launchrctl/launchr@v0.12.0/app.go:213 +0x862
github.com/launchrctl/launchr.(*appImpl).Execute(0xc0003c0210)
	github.com/launchrctl/launchr@v0.12.0/app.go:306 +0x1c
github.com/launchrctl/launchr.Run(...)
	github.com/launchrctl/launchr@v0.12.0/app.go:330
main.main()
	launchr/main.go:28 +0x54
```

- In project dir it works fine, but if call if from different dir like /home it fails

# Expected
- Executing a launchr command anywhere should not throw an error

**Comment by lexbritvin** [comment]
The issue happens in go pkg dir
```
cd go
launchr
```

Here is the directory structure that may produce incorrectly found actions:
```
find . -type d -name "actions"

./go/pkg/mod/github.com/!proton!mail/go-crypto@v1.0.0/.github/actions
./go/pkg/mod/github.com/!proton!mail/go-crypto@v0.0.0-20230828082145-3c4c8a2d2371/.github/actions
./go/pkg/mod/github.com/docker/docker@v25.0.4+incompatible/.github/actions
./go/pkg/mod/github.com/docker/docker@v25.0.3+incompatible/.github/actions
./go/pkg/mod/github.com/moby/moby@v25.0.4+incompatible/.github/actions
./go/pkg/mod/github.com/moby/moby@v25.0.3+incompatible/.github/actions
./go/pkg/mod/github.com/launchrctl/launchr@v0.13.1/example/actions
./go/pkg/mod/github.com/launchrctl/launchr@v0.13.1/example/actions/platform/actions
./go/pkg/mod/github.com/launchrctl/launchr@v0.13.1/example/actions/integration/application/bus/actions
./go/pkg/mod/github.com/launchrctl/launchr@v0.13.1/example/actions/foundation/software/flatcar/actions
./go/pkg/mod/github.com/launchrctl/web@v0.4.0/platform/actions
./go/pkg/mod/github.com/launchrctl/web@v0.4.0/interaction/actions
./go/pkg/mod/github.com/launchrctl/web@v0.4.0/interaction/applications/actions
./go/pkg/mod/github.com/launchrctl/web@v0.4.0/interaction/applications/roles/actions
./go/pkg/mod/github.com/launchrctl/web@v0.4.0/interaction/applications/roles/messenger/actions
./go/pkg/mod/github.com/launchrctl/web@v0.4.0/interaction/applications/roles/erp/actions
./go/pkg/mod/github.com/launchrctl/web@v0.4.0/interaction/applications/roles/mail/actions
./go/pkg/mod/github.com/launchrctl/web@v0.4.0/client/src/pages/actions
./go/pkg/mod/github.com/launchrctl/web@v0.4.0/rjsf/actions
./go/pkg/mod/github.com/launchrctl/web@v0.4.0/foundation/software/flatcar/actions
./go/pkg/mod/github.com/containerd/containerd@v1.7.14/.github/actions
./go/pkg/mod/google.golang.org/genproto@v0.0.0-20230711160842-782d3b101e98/googleapis/actions
```
